export const ActionTypes = {
  GET_HEROES: 'GET_HEROES',
  GET_HEROES_SUCCESS: 'GET_HEROES_SUCCESS',
  GET_HEROES_ERROR: 'GET_HEROES_ERROR',

  CREATE_HERO: 'CREATE_HERO',
  CREATE_HERO_SUCCESS: 'CREATE_HERO_SUCCESS',
  CREATE_HERO_ERROR: 'CREATE_HERO_ERROR',

  DELETE_HERO: 'DELETE_HERO',
  DELETE_HERO_SUCCESS: 'DELETE_HERO_SUCCESS',
  DELETE_HERO_ERROR: 'DELETE_HERO_ERROR',

  UPDATE_HERO: 'DELETE_HERO',
  UPDATE_HERO_SUCCESS: 'UPDATE_HERO_SUCCESS',
  UPDATE_HERO_ERROR: 'UPDATE_HERO_ERROR'
};
